% Deterministic ASTRO invariant smoke checks.
%
% Batch command:
%   matlab -batch "run('tests/run_smoke_tests.m')"

smoke_script = mfilename('fullpath');
tests_dir = fileparts(smoke_script);
repo_root = fileparts(tests_dir);
addpath(repo_root);

assert_unsupported_solver_error(repo_root, 0);
assert_unsupported_solver_error(repo_root, 2);
assert_deterministic_initialization();
assert_production_result_schema();

benchmark_mode = 'quick';
benchmark_output_root = tempname;
run(fullfile(repo_root, 'benchmark', 'run_baseline_benchmark.m'));

result_file = fullfile(benchmark_output_root, 'output', 'benchmark_result.mat');
fixed_atomtype_file = fullfile(repo_root, 'benchmark', 'baseline', ...
    'input', 'baseline_atomtype_quick.mat');

result = load(result_file);
fixed_atomtype = load(fixed_atomtype_file);
defaults = astro_default_config();

assert_smoke(isequal(result.atomtype_, fixed_atomtype.atomtype_), ...
    'Smoke atom distribution does not match fixed quick benchmark input.');
assert_smoke(result.natomW == fixed_atomtype.natomW && ...
    result.natomL == fixed_atomtype.natomL, ...
    'Smoke atom distribution dimensions do not match fixed input metadata.');
assert_smoke(result.compositionn == fixed_atomtype.compositionn, ...
    'Smoke composition does not match fixed input metadata.');
assert_smoke(result.compositionn == defaults.compositionn, ...
    'Smoke composition does not match shared production defaults.');
assert_smoke(result.d == defaults.d && result.tstep == defaults.tstep && ...
    result.gpusave == defaults.gpusave && ...
    result.gpurun_number == defaults.gpurun_number && ...
    result.savetstep == defaults.savetstep, ...
    'Smoke time or lattice-spacing settings do not match shared defaults.');
assert_smoke(result.bc == defaults.bc && result.rk4 == defaults.rk4, ...
    'Smoke solver or boundary settings do not match shared defaults.');
assert_smoke(result.parameter_snapshot.Ksim == defaults.Ksim && ...
    result.parameter_snapshot.Jgdgd == defaults.Jgdgd && ...
    result.parameter_snapshot.Jfefe == defaults.Jfefe && ...
    result.parameter_snapshot.Jfegd == defaults.Jfegd && ...
    result.parameter_snapshot.Dsim == defaults.Dsim && ...
    result.parameter_snapshot.alp == defaults.alp && ...
    result.parameter_snapshot.T == defaults.T && ...
    result.parameter_snapshot.thetaSH == defaults.thetaSH && ...
    result.parameter_snapshot.etaSTT == defaults.etaSTT && ...
    isequal(result.parameter_snapshot.Hext, defaults.Hext) && ...
    isequal(result.parameter_snapshot.psjSHE, defaults.psjSHE) && ...
    isequal(result.parameter_snapshot.psjSTT, defaults.psjSTT), ...
    'Smoke parameter snapshot does not match shared defaults.');
assert_smoke(all(result.atomtype_(:) == 0 | result.atomtype_(:) == 1), ...
    'Smoke atom distribution contains values other than 0 and 1.');

expected_gd_site_count = round(result.natomW*result.natomL* ...
    result.compositionn);
expected_tm_site_count = result.natomW*result.natomL - ...
    expected_gd_site_count;
assert_smoke(nnz(result.atomtype_ == 1) == expected_gd_site_count, ...
    'Smoke Gd site count does not match deterministic composition.');
assert_smoke(nnz(result.atomtype_ == 0) == expected_tm_site_count, ...
    'Smoke TM site count does not match deterministic composition.');
assert_smoke(result.gd_site_count == expected_gd_site_count && ...
    result.tm_site_count == expected_tm_site_count, ...
    'Smoke result site-count metadata does not match atom distribution.');

expected_saved_count = round(result.runtime/result.tstep/result.savetstep) + 1;
expected_trajectory_size = [result.natomW, result.natomL, ...
    expected_saved_count];
assert_smoke(isequal(size(result.mmx), expected_trajectory_size), ...
    'Smoke mmx trajectory dimensions are incorrect.');
assert_smoke(isequal(size(result.mmy), expected_trajectory_size), ...
    'Smoke mmy trajectory dimensions are incorrect.');
assert_smoke(isequal(size(result.mmz), expected_trajectory_size), ...
    'Smoke mmz trajectory dimensions are incorrect.');
assert_smoke(numel(result.t) == expected_saved_count, ...
    'Smoke saved time count does not match expected saved count.');
assert_smoke(numel(result.t) == size(result.mmx, 3) && ...
    numel(result.t) == size(result.mmy, 3) && ...
    numel(result.t) == size(result.mmz, 3), ...
    'Smoke saved time count does not match saved state count.');

assert_smoke(all(isfinite(result.mmx(:))) && ...
    all(isfinite(result.mmy(:))) && all(isfinite(result.mmz(:))), ...
    'Smoke trajectory contains non-finite spin values.');

spin_norm = sqrt(result.mmx.^2 + result.mmy.^2 + result.mmz.^2);
spin_norm_tolerance = 1e-10;
assert_smoke(max(abs(spin_norm(:) - 1)) <= spin_norm_tolerance, ...
    'Smoke spin normalization check failed.');

time_tolerance = eps(result.runtime);
assert_smoke(result.t(1) == 0, 'Smoke saved times do not start at t=0.');
assert_smoke(abs(result.t(end) - result.runtime) <= time_tolerance, ...
    'Smoke saved times do not end at runtime.');
assert_smoke(all(diff(result.t) > 0), ...
    'Smoke saved times are not strictly increasing.');

fprintf('ASTRO smoke checks passed.\n');
fprintf('Result checked: %s\n', result_file);
fprintf('Saved states: %d\n', expected_saved_count);
fprintf('Max spin-norm error: %.6e\n', max(abs(spin_norm(:) - 1)));

function assert_unsupported_solver_error(repo_root, unsupported_rk4)
expected_message = sprintf(['Unsupported ASTRO solver mode rk4=%g. ' ...
    'Only rk4=1 (RK4) is supported. rk4=0 (Heun) and rk4=2 ' ...
    '(predictor-corrector) are disabled because they are not validated ' ...
    'production paths.'], unsupported_rk4);
try
    rk4 = unsupported_rk4;
    run(fullfile(repo_root, 'integrate_llg.m'));
catch solver_error
    assert_smoke(strcmp(solver_error.identifier, ...
        'ASTRO:UnsupportedSolver'), ...
        sprintf('Unsupported solver rk4=%g failed with the wrong identifier.', ...
        unsupported_rk4));
    assert_smoke(strcmp(solver_error.message, expected_message), ...
        sprintf('Unsupported solver rk4=%g failed with the wrong message.', ...
        unsupported_rk4));
    return
end
error('Unsupported solver rk4=%g did not fail.', unsupported_rk4);
end

function assert_deterministic_initialization()
atomtype_ = [0 1 0 1 0; 1 0 1 0 1; 0 0 1 1 0];
natomW = 3;
natomL = 5;
compositionn = nnz(atomtype_ == 1)/(natomW*natomL);

validated_atomtype = astro_validate_atom_distribution(atomtype_, natomW, ...
    natomL, compositionn);
assert_smoke(isequal(validated_atomtype, atomtype_), ...
    'Deterministic atom distribution validation changed atomtype_.');

[mx_dw, my_dw, mz_dw] = astro_initial_spin_state(atomtype_, natomW, ...
    natomL, true);
[expected_mx_dw, expected_my_dw, expected_mz_dw] = ...
    legacy_initial_spin_state(atomtype_, natomW, natomL, true);
assert_smoke(isequal(mx_dw, expected_mx_dw) && ...
    isequal(my_dw, expected_my_dw) && isequal(mz_dw, expected_mz_dw), ...
    'Deterministic domain-wall initialization changed exact output.');

[mx_uniform, my_uniform, mz_uniform] = astro_initial_spin_state( ...
    atomtype_, natomW, natomL, false);
[expected_mx_uniform, expected_my_uniform, expected_mz_uniform] = ...
    legacy_initial_spin_state(atomtype_, natomW, natomL, false);
assert_smoke(isequal(mx_uniform, expected_mx_uniform) && ...
    isequal(my_uniform, expected_my_uniform) && ...
    isequal(mz_uniform, expected_mz_uniform), ...
    'Deterministic uniform initialization changed exact output.');

assert_invalid_atom_distribution(atomtype_(1:2, :), natomW, natomL, ...
    compositionn, 'size');
invalid_values = atomtype_;
invalid_values(1, 1) = 2;
assert_invalid_atom_distribution(invalid_values, natomW, natomL, ...
    compositionn, 'values');
invalid_composition = atomtype_;
invalid_composition(1, 1) = 1;
assert_invalid_atom_distribution(invalid_composition, natomW, natomL, ...
    compositionn, 'composition');
end

function [mx_init, my_init, mz_init] = legacy_initial_spin_state( ...
        atomtype_, natomW, natomL, dwcalc)
mx_init = zeros(natomW, natomL);
my_init = zeros(natomW, natomL);
mz_init = zeros(natomW, natomL);

if dwcalc
    phi_ = 0;
    for ctL = 1:natomL
        for ctW = 1:natomW
            if ctL < round(natomL/2)
                if atomtype_(ctW, ctL) == 0
                    thet_ = 5/180*pi;
                else
                    thet_ = (5 + 180)/180*pi;
                end
                mx_init(ctW, ctL) = sin(thet_)*cos(phi_);
                my_init(ctW, ctL) = sin(thet_)*sin(phi_);
                mz_init(ctW, ctL) = cos(thet_);
            else
                if atomtype_(ctW, ctL) == 0
                    thet_ = (5 + 180)/180*pi;
                else
                    thet_ = 5/180*pi;
                end
                mx_init(ctW, ctL) = sin(thet_)*cos(phi_);
                my_init(ctW, ctL) = sin(thet_)*sin(phi_);
                mz_init(ctW, ctL) = cos(thet_);
            end
        end
    end
else
    phi_ = 0;
    for ctL = 1:natomL
        for ctW = 1:natomW
            if atomtype_(ctW, ctL) == 0
                thet_ = 5/180*pi;
            else
                thet_ = (5 + 180)/180*pi;
            end
            mx_init(ctW, ctL) = sin(thet_)*cos(phi_);
            my_init(ctW, ctL) = sin(thet_)*sin(phi_);
            mz_init(ctW, ctL) = cos(thet_);
        end
    end
end
end

function assert_invalid_atom_distribution(atomtype_, natomW, natomL, ...
        compositionn, case_name)
try
    astro_validate_atom_distribution(atomtype_, natomW, natomL, ...
        compositionn);
catch validation_error
    assert_smoke(strcmp(validation_error.identifier, ...
        'ASTRO:InvalidAtomDistribution'), ...
        sprintf('Invalid atom distribution %s failed with wrong identifier.', ...
        case_name));
    return
end
error('Invalid atom distribution %s did not fail.', case_name);
end

function assert_production_result_schema()
config = astro_default_config();
config.natomW = 2;
config.natomL = 2;
config.natom = 4;
config.gpusteps = 1;
config.runtime = config.tstep;
config.totstep = 1;
config.final_m_savestep = 2;

atomtype_ = [0 1; 1 0];
mx_init = ones(2, 2);
my_init = zeros(2, 2);
mz_init = zeros(2, 2);
mmx = zeros(2, 2, 2);
mmy = zeros(2, 2, 2);
mmz = zeros(2, 2, 2);
mmx(:, :, 1) = mx_init;
mmy(:, :, 1) = my_init;
mmz(:, :, 1) = mz_init;
mmx(:, :, 2) = mx_init;
mmy(:, :, 2) = my_init;
mmz(:, :, 2) = mz_init;
t = [0, config.runtime];
output_file = [tempname, '.mat'];

astro_result = astro_build_production_result(config, atomtype_, mx_init, ...
    my_init, mz_init, mmx, mmy, mmz, t, 0, output_file);
save(output_file, 'astro_result');

saved_variables = whos('-file', output_file);
assert_smoke(numel(saved_variables) == 1 && ...
    strcmp(saved_variables.name, 'astro_result'), ...
    'Production result file should contain only astro_result.');
result = load(output_file);
result = result.astro_result;

required_sections = {'schema_name', 'schema_version', 'configuration', ...
    'atom_distribution', 'initial_state', 'trajectory', 'timestamps', ...
    'provenance'};
assert_smoke(all(isfield(result, required_sections)), ...
    'Production result schema is missing required top-level sections.');
assert_smoke(strcmp(result.schema_version, '1.0'), ...
    'Production result schema version changed unexpectedly.');
assert_smoke(isequal(result.atom_distribution.atomtype_, atomtype_), ...
    'Production result atom distribution changed.');
assert_smoke(isequal(result.initial_state.mx, mx_init) && ...
    isequal(result.initial_state.my, my_init) && ...
    isequal(result.initial_state.mz, mz_init), ...
    'Production result initial state changed.');
assert_smoke(isequal(result.trajectory.mx, mmx) && ...
    isequal(result.trajectory.my, mmy) && ...
    isequal(result.trajectory.mz, mmz) && ...
    isequal(result.trajectory.t, t), ...
    'Production result trajectory changed.');
assert_smoke(numel(result.timestamps.trajectory_time_s) == ...
    size(result.trajectory.mx, 3), ...
    'Production result timestamp count does not match trajectory depth.');
assert_smoke(result.atom_distribution.gd_site_count == 2 && ...
    result.atom_distribution.tm_site_count == 2, ...
    'Production result atom counts are incorrect.');
assert_smoke(~isfield(result, 'Ksim') && ~isfield(result, 'mmx'), ...
    'Production result leaked workspace-style top-level variables.');
end

function assert_smoke(condition, message)
if ~condition
    error(message);
end
end
